export type AiTaskType =
  | 'clinical_document'
  | 'clinical_review'
  | 'clinical_advice'
  | 'clinical_reference'
  | 'clinical_guideline_comparison'
  | 'clinical_source_check'
  | 'pikaohje_generation'
  | 'pikaohje_review'
  | 'medication_guidance'
  | 'urgent_triage'
  | 'referral_guidance'
  | 'text_fix'
  | 'translation'
  | 'template_generation