import type { PrivacyLocalePack } from './types';

export const privacyPackDe: PrivacyLocalePack = {
  locale: 'de',
  personContextWords: [
    'patient',
    'patientin',
    'name',
    'vorname',
    'nachname',
    'geboren',
    'geburtsdatum',
    'geburtsname',
    'email',
    'e-mail',
    'telefon',
    'handy',
    'mobil',
    'adresse',
    'anschrift',
    'ehefrau',
    'ehemann',
    'partner',
    'kind',
    'mutter',
    'vater',
    'angehoerige',
    'angehörige',
    'betreuer',
  ],
  dateOfBirthLabels: ['geburtsdatum', 'geboren', 'geb\\.'],
  explicitNameLabels: ['patient', 'patientin', 'name', 'vollstaendiger name', 'vollständiger name'],
  patientIdLabels: ['patienten-id', 'patientennummer', 'fallnummer', 'aktennummer', 'versichertennummer'],
  phoneLabels: ['telefon', 'telefonnummer', 'handy', 'mobil', 'kontakt'],
  phoneValuePatterns: [
    '(?:\\+49|0)\\s?(?:\\d[\\s./-]*){7,13}\\d',
  ],
  notes: 'German privacy pack for clinical text and imported patient records.',
};
