import type { PrivacyLocalePack } from './types';

export const privacyPackFi: PrivacyLocalePack = {
  locale: 'fi',
  personContextWords: [
    'potilas',
    'potilaan',
    'nimi',
    'syntynyt',
    'synt\\.',
    's\\.',
    'syntymäaika',
    'henkilötunnus',
    'hetu',
    'sähköposti',
    'puhelin',
    'osoite',
    'vaimo',
    'puoliso',
    'aviopuoliso',
    'mies',
    'nainen',
    'tyttö',
    'poika',
    'lapsi',
    'äiti',
    'isä',
    'tytär',
    'veli',
    'sisko',
    'sisar',
    'omainen',
    'lähiomainen',
    'huoltaja',
  ],
  dateOfBirthLabels: ['syntynyt', 'synt\\.', 's\\.', 'syntymäaika'],
  explicitNameLabels: ['potilaan nimi', 'nimi'],
  patientIdLabels: ['potilasnumero', 'potilasnro', 'henkilönumero', 'henkilönro', 'asiakasnumero', 'asiakasnro'],
  phoneLabels: ['puhelin', 'puhelinnumero', 'puh\\.', 'gsm'],
  phoneValuePatterns: ['(?:\\+358|0)\\s?(?:4\\d|[1-9]\\d?)\\s?(?:\\d\\s?){5,8}'],
  notes: 'Finnish privacy pack for clinical text pasted by healthcare professionals.',
};
