import type { PrivacyLocalePack } from './types';

export const privacyPackRu: PrivacyLocalePack = {
  locale: 'ru',
  personContextWords: [
    'пациент',
    'пациента',
    'пациентка',
    'пациентки',
    'имя',
    'фио',
    'ф\\.и\\.о\\.',
    'дата рождения',
    'д\\.р\\.',
    'др',
    'почта',
    'телефон',
    'тел\\.',
    'адрес',
    'муж',
    'жена',
    'мальчик',
    'девочка',
    'ребенок',
    'мать',
    'отец',
    'родственник',
    'опекун',
  ],
  dateOfBirthLabels: ['дата рождения', 'д\\.р\\.', 'др'],
  explicitNameLabels: [
    'имя',
    'имя пациента',
    'имя пациентки',
    'фио',
    'ф\\.и\\.о\\.',
  ],
  patientIdLabels: ['номер пациента', 'id пациента', 'номер карты'],
  phoneLabels: ['телефон', 'тел\\.', 'моб\\.', 'мобильный', 'номер телефона'],
  phoneValuePatterns: [
    '(?:\\+7|8)\\s*(?:\\(\\s*\\d{3}\\s*\\)|\\d{3})[\\s-]*\\d{3}[\\s-]*\\d{2}[\\s-]*\\d{2}',
  ],
  notes: 'Russian privacy pack for imported or mixed-language notes.',
};
