import type { PrivacyLocalePack } from './types';

export const privacyPackRu: PrivacyLocalePack = {
  locale: 'ru',
  personContextWords: [
    'пациент',
    'пациента',
    'пациентка',
    'пациентки',
    'имя',
    'фио',
    'ф\\.и\\.о\\.',
    'дата рождения',
    'д\\.р\\.',
    'др',
    'почта',
    'телефон',
    'тел\\.',
    'адрес',
    'муж',
    'жена',
    'мальчик',
    'девочка',
    'ребенок',
    'мать',
    'отец',
    'родственник',
    'опекун',
  ],
  dateOfBirthLabels: ['дата рождения', 'д\\.р\\.', 'др'],
  explicitNameLabels: ['пациент', 'пациентка', 'имя', 'фио', 'ф\\.и\\.о\\.'],
  patientIdLabels: ['номер пациента', 'id пациента', 'номер карты'],
  notes: 'Russian privacy pack for imported or mixed-language notes.',
};
